package com.agrilink.sms;

public enum SmsType {
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    AWAITING_PAYMENT,
    PAYMENT_CONFIRMED,
    LOGISTICS_ARRANGED,
    IN_TRANSIT,
    DELIVERED,
    PAYOUT_PROCESSED,
    OFFER_EXPIRED,
    STORAGE_COST_REMINDER,
    WITHDRAWAL_PROCESSED
}