CREATE TABLE transactions (
                              transaction_id VARCHAR(100) NOT NULL,
                              produce_id VARCHAR(100) NOT NULL,
                              farmer_id VARCHAR(50) NOT NULL,
                              buyer_id VARCHAR(50) NOT NULL,
                              agent_id VARCHAR(50),
                              status VARCHAR(30) NOT NULL,
                              offered_price DOUBLE NOT NULL,
                              quantity_sold DOUBLE,
                              commission_amount DOUBLE,
                              storage_cost_deducted DOUBLE,
                              farmer_net_payout DOUBLE,
                              logistics_partner VARCHAR(100),
                              logistics_tracking_number VARCHAR(100),
                              payment_reference VARCHAR(100),
                              offer_response_deadline DATETIME,
                              payment_confirmed_at DATETIME,
                              logistics_confirmed_at DATETIME,
                              delivered_at DATETIME,
                              paid_to_farmer_at DATETIME,
                              created_at DATETIME,
                              updated_at DATETIME,
                              PRIMARY KEY (transaction_id)
);